version: '3.1'
services:
  prometheus:
    image: quay.io/prometheus/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./.podman-compose/prometheus/config:/etc/prometheus:z
      - ./.podman-compose/prometheus/data:/prometheus:z
    command:
    - "--config.file=/etc/prometheus/prometheus.yml"
    - "--storage.tsdb.path=/prometheus"
    - "--web.console.libraries=/usr/share/prometheus/console_libraries"
    - "--web.console.templates=/usr/share/prometheus/consoles"
    - "--web.enable-remote-write-receiver"
    restart: always
